import "./globals.css";
import "ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { ReactElement, ReactNode } from "react";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { PageLayout } from "./components/page-layout.tsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}): ReactElement {
  return (
    <html lang="en">
    <UserProvider>
      <body className={inter.className}>
        <PageLayout>{children}</PageLayout>
      </body>
    </UserProvider>
    </html>
  );
}
